version: '3'
services:
  api: 
    container_name: api
    restart: unless-stopped
    build: ./api
    command: npm start
    environment:
      - REQUESTS_TO_RESTART=4
      - KEYWORD="bmw new"
      - INTERVAL=5000
      - DEBUG=true
    depends_on:
      - pg
  pg:
    container_name: pg
    restart: unless-stopped
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=lol
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
