version: '3'
services:
  controller: 
    container_name: controller
    restart: unless-unsopped
    build: ./controller
    command: npm start
    environment:
      - REQUESTS_TO_RESTART=1400
      - KEYWORD="bmw new"
      - INTERVAL=5000
      - DEBUG=false
    depends_on:
      - pg
  pg:
    container_name: pg
    restart: unless-stopped
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=lol
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
